<a href="https://colab.research.google.com/github/Yeshu-18/21CSS101J-PYTHON-COLAB/blob/main/Copy_of_numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr=np.array([3.7,-1.2,-2.6])
print(arr)
print(arr.astype(np.int32))


[ 3.7 -1.2 -2.6]
[ 3 -1 -2]


In [ ]:
print(arr.dtype)

float64


In [ ]:
print(arr.shape)

(3,)


In [ ]:
ar=np.array([1,2.4,2,3,4,5])
print(ar.shape)

(6,)


In [ ]:
a=np.array([1,2])
print(type(a.shape))
print(a.dtype)

<class 'tuple'>
int64


In [ ]:
print(a.astype(float))

[1. 2.]


In [ ]:
print(a)

[1 2]


In [ ]:
print(np.arange(9))
print(ar)

[0 1 2 3 4 5 6 7 8]
[1.  2.4 2.  3.  4.  5. ]


In [ ]:
np.percentile(a,30)
np.percentile(a,50)

1.5

In [ ]:
np.percentile(ar,0)

1.0